# Generated by Django 4.2.7 on 2023-11-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='first_name',
        ),
    ]
