# Generated by Django 4.2.7 on 2023-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidiaryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_image', models.ImageField(upload_to='subsidiary_images')),
            ],
        ),
    ]
