# Generated by Django 4.2.7 on 2023-12-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiary', '0003_rename_welcome_image_subsidiaryimages_welcomeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiaryimages',
            name='propertyDevelopment',
            field=models.ImageField(default='default.jpg', upload_to='property_development_images'),
        ),
    ]
