# Generated by Django 4.2.7 on 2024-03-03 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidiary', '0012_accountingimage_user_cleaningimage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingimage',
            name='welcomeImage',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='cleaningimage',
            name='welcomeImage',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='landscapingimage',
            name='welcomeImage',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='propertydevelopmentimage',
            name='welcomeImage',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='suppliesimage',
            name='WelcomeImage',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting3',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting4',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting5',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning3',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning4',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning5',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='contentImage1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='contentImage2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='welcomeImage',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping3',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping4',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping5',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll3',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll4',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll5',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='propertydevelopmentimage',
            name='propertyDevelopment1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='propertydevelopmentimage',
            name='propertyDevelopment2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='propertydevelopmentimage',
            name='propertyDevelopment3',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='propertydevelopmentimage',
            name='propertyDevelopment4',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='propertydevelopmentimage',
            name='propertyDevelopment5',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='subsidiaryimage',
            name='welcomeImage',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies3',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies4',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies5',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax1',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax2',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax3',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax4',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax5',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.CreateModel(
            name='BusinessConsultingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax1', models.ImageField(default='default.jpg', upload_to=None)),
                ('tax2', models.ImageField(default='default.jpg', upload_to=None)),
                ('tax3', models.ImageField(default='default.jpg', upload_to=None)),
                ('tax4', models.ImageField(default='default.jpg', upload_to=None)),
                ('tax5', models.ImageField(default='default.jpg', upload_to=None)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
