# Generated by Django 4.2.7 on 2024-03-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiary', '0013_accountingimage_welcomeimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeimage',
            old_name='contentImage2',
            new_name='contactUsImage',
        ),
    ]
