# Generated by Django 4.2.7 on 2024-03-08 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidiary', '0015_rename_accounting1_accountingimage_accounting_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Welcome_Image', models.ImageField(default='default.jpg', upload_to=None)),
                ('businessConsulting_1', models.ImageField(default='default.jpg', upload_to=None)),
                ('businessConsulting_2', models.ImageField(default='default.jpg', upload_to=None)),
                ('businessConsulting_3', models.ImageField(default='default.jpg', upload_to=None)),
                ('businessConsulting_4', models.ImageField(default='default.jpg', upload_to=None)),
                ('businessConsulting_5', models.ImageField(default='default.jpg', upload_to=None)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
