# Generated by Django 4.2.7 on 2024-03-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiary', '0016_manufacturingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturingimage',
            old_name='businessConsulting_1',
            new_name='manufacturing_1',
        ),
        migrations.RenameField(
            model_name='manufacturingimage',
            old_name='businessConsulting_2',
            new_name='manufacturing_2',
        ),
        migrations.RenameField(
            model_name='manufacturingimage',
            old_name='businessConsulting_3',
            new_name='manufacturing_3',
        ),
        migrations.RenameField(
            model_name='manufacturingimage',
            old_name='businessConsulting_4',
            new_name='manufacturing_4',
        ),
        migrations.RenameField(
            model_name='manufacturingimage',
            old_name='businessConsulting_5',
            new_name='manufacturing_5',
        ),
    ]
