# Generated by Django 4.2.7 on 2023-12-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiary', '0002_subsidiaryimages_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidiaryimages',
            old_name='welcome_image',
            new_name='welcomeImage',
        ),
    ]
