# Generated by Django 4.2.7 on 2023-12-08 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidiary', '0007_homeimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning1', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('cleaning2', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('cleaning3', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('cleaning4', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('cleaning5', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandscapingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscaping1', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('landscaping2', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('landscaping3', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('landscaping4', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('landscaping5', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDevelopmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyDevelopment1', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('propertyDevelopment2', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('propertyDevelopment3', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('propertyDevelopment4', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('propertyDevelopment5', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubsidiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcomeImage', models.ImageField(upload_to='subsidiary_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuppliesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplies1', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('supplies2', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('supplies3', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('supplies4', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('supplies5', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='HomeImages',
            new_name='HomeImage',
        ),
        migrations.DeleteModel(
            name='SubsidiaryImages',
        ),
    ]
