# Generated by Django 4.2.7 on 2024-01-03 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidiary', '0008_cleaningimage_landscapingimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax1', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('tax2', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('tax3', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('tax4', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('tax5', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll1', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('payroll2', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('payroll3', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('payroll4', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('payroll5', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting1', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('accounting2', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('accounting3', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('accounting4', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('accounting5', models.ImageField(default='default.jpg', upload_to='property_development_images')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
