# Generated by Django 4.2.7 on 2024-01-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiary', '0009_taximage_payrollimage_accountingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cleaningimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='landscapingimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payrollimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='propertydevelopmentimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subsidiaryimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suppliesimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taximage',
            name='user',
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting1',
            field=models.ImageField(default='default.jpg', upload_to='accounting_images'),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting2',
            field=models.ImageField(default='default.jpg', upload_to='accounting_images'),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting3',
            field=models.ImageField(default='default.jpg', upload_to='accounting_images'),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting4',
            field=models.ImageField(default='default.jpg', upload_to='accounting_images'),
        ),
        migrations.AlterField(
            model_name='accountingimage',
            name='accounting5',
            field=models.ImageField(default='default.jpg', upload_to='accounting_images'),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning1',
            field=models.ImageField(default='default.jpg', upload_to='cleaning_images'),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning2',
            field=models.ImageField(default='default.jpg', upload_to='cleaning_images'),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning3',
            field=models.ImageField(default='default.jpg', upload_to='cleaning_images'),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning4',
            field=models.ImageField(default='default.jpg', upload_to='cleaning_images'),
        ),
        migrations.AlterField(
            model_name='cleaningimage',
            name='cleaning5',
            field=models.ImageField(default='default.jpg', upload_to='cleaning_images'),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping1',
            field=models.ImageField(default='default.jpg', upload_to='landscaping_images'),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping2',
            field=models.ImageField(default='default.jpg', upload_to='landscaping_images'),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping3',
            field=models.ImageField(default='default.jpg', upload_to='landscaping_images'),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping4',
            field=models.ImageField(default='default.jpg', upload_to='landscaping_images'),
        ),
        migrations.AlterField(
            model_name='landscapingimage',
            name='landscaping5',
            field=models.ImageField(default='default.jpg', upload_to='landscaping_images'),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll1',
            field=models.ImageField(default='default.jpg', upload_to='payroll_images'),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll2',
            field=models.ImageField(default='default.jpg', upload_to='payroll_images'),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll3',
            field=models.ImageField(default='default.jpg', upload_to='payroll_images'),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll4',
            field=models.ImageField(default='default.jpg', upload_to='payroll_images'),
        ),
        migrations.AlterField(
            model_name='payrollimage',
            name='payroll5',
            field=models.ImageField(default='default.jpg', upload_to='payroll_images'),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies1',
            field=models.ImageField(default='default.jpg', upload_to='supplies_images'),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies2',
            field=models.ImageField(default='default.jpg', upload_to='supplies_images'),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies3',
            field=models.ImageField(default='default.jpg', upload_to='supplies_images'),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies4',
            field=models.ImageField(default='default.jpg', upload_to='supplies_images'),
        ),
        migrations.AlterField(
            model_name='suppliesimage',
            name='supplies5',
            field=models.ImageField(default='default.jpg', upload_to='supplies_images'),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax1',
            field=models.ImageField(default='default.jpg', upload_to='tax_images'),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax2',
            field=models.ImageField(default='default.jpg', upload_to='tax_images'),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax3',
            field=models.ImageField(default='default.jpg', upload_to='tax_images'),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax4',
            field=models.ImageField(default='default.jpg', upload_to='tax_images'),
        ),
        migrations.AlterField(
            model_name='taximage',
            name='tax5',
            field=models.ImageField(default='default.jpg', upload_to='tax_images'),
        ),
    ]
