# Generated by Django 4.2.7 on 2024-01-06 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidiary', '0010_remove_accountingimage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
